#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo '🏗️👷 Styling, testing and building your project before committing'

yarn pre-commit


# If everything passes... Now we can commit
echo '✅✅✅✅ No issues found. ✅✅✅✅'